### ISSUE TITLE
한국어 번역 파일의 잘못된 `msgid` 및 `msgstr`

### ISSUE THREAD

**Issue by imjlk** [chwnam/naran-boilerplate#98]
https://github.com/chwnam/naran-boilerplate/blob/615810674ce2fc04b32e50f5850d841f78e24a8c/languages/nbpc-ko_KR.po#L24-L31

한국어 번역 파일 `nbpc-ko_KR.po` 에서 위 라인에 해당되는 문자열이 잘못된 것처럼 보입니다. (이 경우 정상적으로 출력이 되는지 궁금하네요)

`pot`파일의 경우 정상적인 것으로 보입니다.

아마 코드 포맷팅 과정에서 `.po` 파일 형식도 코드 라인 최대 문자 제한이 적용 된 것이 아닐까요?

**Comment by chwnam** [comment]
PO, POT 파일은 툴에 의해서 작성된 것이며 잘못되지 않았습니다. 

msgid, msgstr 의 경우 여러 줄로 사용할 수 있으며 이 경우 위처럼 사용합니다.

> Each of untranslated-string and translated-string respects the C syntax for a character string, including the surrounding quotes and embedded backslashed escape sequences. When the time comes to write multi-line strings, one should not use escaped newlines. Instead, a closing quote should follow the last character on the line to be continued, and an opening quote should resume the string at the beginning of the following PO file line. For example:

> msgid ""
> "Here is an example of how one might continue a very long string\n"
> "for the common case the string represents multi-line output.\n"

https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

**Comment by imjlk** [comment]
확인 감사합니다. 하나 또 배워갑니다 🙇‍♂️
