### ISSUE TITLE
composer 구성 문의

### ISSUE THREAD

**Issue by imjlk** [chwnam/naran-boilerplate#99]
1. composer를 사용하여 설치를 진행할 경우 1.4.3 버전으로 설치가 됩니다. (git clone으로 최신 버전을 받을 수 있지만 동일하게 지원되면 좋을 것 같네요)
2. `composer.json`에서 php버전 명시가 캐럿 기호로 고정되어 있어서 php 8.x버전 환경에서 아래와 같이 인스톨 진행이 되지 않습니다. 
```
$ composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit[7.0.0, ..., 7.5.20] require php ^7.1 -> your php version (8.1.6) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^7 -> satisfiable by phpunit/phpunit[7.0.0, ..., 7.5.20].
```

제 경우 https://github.com/chwnam/naran-boilerplate/blob/615810674ce2fc04b32e50f5850d841f78e24a8c/composer.json#L51-L58 이 부분을 아래 내용처럼 수정해서 설치 진행이 가능했습니다
```
...
  "require": {
    "php": ">=7.4",
    "ext-json": "*",
    "ext-zip": "*"
  },
  "version": "1.5.4",
  "require-dev": {
    "phpunit/phpunit": ">=7",
...
```

**Comment by chwnam** [comment]
제 프로젝트에 관심을 가져주셔서 정말 감사합니다.

![image](https://user-images.githubusercontent.com/6630320/175899000-33388b8b-f934-415f-962f-d35595cf8e94.png)

`composer create-project naran/boilerplate` 로 했을 때 1.5.4 버전이 정상적으로 설치됩니다. 위 스크린샷처럼 packagist 쪽에서도 1.5.4로 인식되고 있고요.


PHP8은 그렇게 수정하셔서 진행하시면 됩니다. 사실 이건 보일러플레이트 코드고, PHP 지원 여부나 이런 것들은 제가 엄격하게 제한할 것은 아닌 것 같다고 생각을 하고 있습니다.

사실은 저도 PHP 8, 8.1 의 급진적인 문법들을 마구 가져다 사용하고 싶습니다. 요즘은 어지간한 laravel이나 symphony 최신 콤포넌트들도 다 8 이상을 지원하서 좀 안절부절합니다. 하지만 실제 프로젝트에서 아직 8을 쓰기에 시기상조인 부분도 많이 발견됩니다. 몇몇 문제가 있어 여전히 보수적으로 7.4에 머물러 있습니다.

제가 생각할 때 PHP 8.0 이상을 지원하지 않은 가장 크리티컬한 이유는 유닛 테스트입니다.제 보일러플레이트는 유닛 테스트를 위해 `wp scaffold plugin-tests` 라는 WP CLI 기능을 사용합니다. 이 때 워드프레스의 개발 SVN 에서 PhpUnit 테스트 수트를 받아서 워드프레스를 위한 테스트용 기능을 추가합니다.

이 때 이 테스트 수트가 오래된 PhpUnit 7.x 버전을 지원하고 있고, 이게 PHP8을 지원하지 않고 있습니다. 최근 변경되었는지 확인하지는 않았지만, 제가 알고 있는 한 그렇습니다. 워드프레스에서 유닛 테스트를 완전히 포기한다면 말씀하신 것처럼 PHP 8을 지원하게 하는 것도 무방합니다만, 테스트 코드를 염두한다면 저는 그래도 PHP7.4를 쓰는 것을 추천하고 있습니다.

**Comment by imjlk** [comment]
상세한 답변 감사드립니다! 다시 확인해보니 윈도우 환경에서만 `composer create-project naran/boilerplate` 이 명령어로 받아온 경우에도 동일하게 1.4.3 버전으로 설치가 진행되네요. WSL에서는 말씀해주신것처럼 최신 버전으로 잘 반영이 되는데, 제 윈도우 환경에서 무언가 문제가 있는지 확인해봐야 될 것 같습니다.
